name: kore
version: '1.0-SNAPSHOT'
main: com.altoflora.Kore
api-version: '1.20'
authors: [ Altoflora TEAM ]
commands:
  micuenta:
    description: Responde con el nombre de cuenta proporcionado.
    usage: /micuenta <nombre>
  playerinfo:
    description: Responde con el nombre de cuenta proporcionado.
    usage: /playerinfo <nombre>
  playeroffline:
    description: Responde con el nombre de cuenta proporcionado.
    usage: /playeroffline <nombre>